### ISSUE TITLE
What about assignment 3? 

### ISSUE THREAD

**Issue by simonelnahas** [m2mtech/calculator-2017#1]
do you have anything on that?

**Comment by Abuzar-93** [comment]
@m2mtech , we badly need the Assignment 3,

**Comment by m2mtech** [comment]
Sorry, nothing yet. My customers require all my attention. ... and then I should update the other assignments for Swift 4, too ;)

**Comment by simonelnahas** [comment]
would be nice


Venlig Hilsen


Simon El Nahas Christensen

Danmarks Tekniske Universitet

________________________________
Fra: m2m tech <notifications@github.com>
Sendt: 24. september 2017 16:03:57
Til: m2mtech/calculator-2017
Cc: Simon El Nahas Christensen; Author
Emne: Re: [m2mtech/calculator-2017] What about assignment 3? (#1)


Sorry, nothing yet. My customers require all my attention. ... and then I should update the other assignments for Swift 4, too ;)

**Comment by simonelnahas** [comment]
if you could start out just uploading it, then make the guide later on :)

**Comment by m2mtech** [comment]
@s163951 No problem, please clone the repository, checkin your code and start a merge request ;)
Have a nice weekend
  Martin

**Comment by simonelnahas** [comment]
> if _**you**_ could start out just uploading it, then make the guide later on :)

**Comment by m2mtech** [comment]
@s163951  All code I have, is already uploaded, now it's time for you to give back to the community and share your code

**Comment by kunjanimamu123** [comment]
Hey, do you have the assignment 3? Can you post it? thanks!

**Comment by m2mtech** [comment]
@kunjanimamu123 same as before: nope
